name:                 dbsp-hs
version:              0.1.0.0
visibility:           public
id:                   dbsp-hs-0.1.0.0-inplace
key:                  dbsp-hs-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           113939131+jkr11@users.noreply.github.com
author:               jkr11
category:             Database
abi:                  inplace
exposed:              True
exposed-modules:      DBSP.Core DBSP.Stream MyLib
import-dirs:
    /home/jkr/algorithms/dbsp-hs/dist-newstyle/build/x86_64-linux/ghc-9.4.8/dbsp-hs-0.1.0.0/build

library-dirs:
    /home/jkr/algorithms/dbsp-hs/dist-newstyle/build/x86_64-linux/ghc-9.4.8/dbsp-hs-0.1.0.0/build

library-dirs-static:
    /home/jkr/algorithms/dbsp-hs/dist-newstyle/build/x86_64-linux/ghc-9.4.8/dbsp-hs-0.1.0.0/build

dynamic-library-dirs:
    /home/jkr/algorithms/dbsp-hs/dist-newstyle/build/x86_64-linux/ghc-9.4.8/dbsp-hs-0.1.0.0/build

data-dir:             /home/jkr/algorithms/dbsp-hs/.
hs-libraries:         HSdbsp-hs-0.1.0.0-inplace
depends:
    base-4.17.2.1 containers-0.6.7
    groups-0.5.3-fc24027248fef2862d94f0e6b7145c7b1de62166df4ff7b58d62d71e71f96154

haddock-interfaces:
    /home/jkr/algorithms/dbsp-hs/dist-newstyle/build/x86_64-linux/ghc-9.4.8/dbsp-hs-0.1.0.0/doc/html/dbsp-hs/dbsp-hs.haddock

haddock-html:
    /home/jkr/algorithms/dbsp-hs/dist-newstyle/build/x86_64-linux/ghc-9.4.8/dbsp-hs-0.1.0.0/doc/html/dbsp-hs
